runator_facebook:
    resource: "@RunatorFacebookBundle/Resources/config/routing.yml"
    prefix:   /

runator_weather:
    resource: "@RunatorWeatherBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
